### ISSUE TITLE
The connection via environmental variables doesn't seem to work correctly

### ISSUE THREAD

**Issue by puzhu** [kineticadb/pretty-trip#5]
I have tried this a few time. The database object is created but I am unable to create a schema or table.

```
KINETICA_HOST = os.getenv('KINETICA_HOST', "http://localhost:9191")
KINETICA_USER = os.getenv('KINETICA_USER', "kadmin")
KINETICA_PASS = os.getenv('KINETICA_PASS')
db = gpudb.GPUdb(host=KINETICA_HOST, username=KINETICA_USER, password=KINETICA_PASS)
exec_result = db.execute_sql_and_decode('show system properties')['status_info']['status']
print(exec_result)
```

It works if I use the connection details on workbench.

![Screen Shot 2021-10-22 at 12 35 23 PM](https://user-images.githubusercontent.com/6342432/138491364-fca7b25a-b821-48af-80f6-c4a49d76d532.png)

**Comment by saifrahmed** [comment]
Note that cloud connection strings have an ingress path. I recommend using the host string from the cloud UI main page.
